### ISSUE TITLE
延迟，识别度低

### ISSUE THREAD

**Issue by Wyrande** [chentyjpm/DarknetDemoInAndroid#1]
您好，我看了您在CSDN上的帖子，已经下载了您的源码并通过AS运行安装到了我的真机里，但是我发现识别不出来，而且延迟很久，请问是否我缺失了什么操作？

**Comment by chentyjpm** [comment]
你可以尝试关闭openmp 测试下 我的手机是armv8 在pc模拟器上出现过你说的这个情况
