### ISSUE TITLE
使用yolov3.weights时app闪退

### ISSUE THREAD

**Issue by nbdwddbf** [chentyjpm/DarknetDemoInAndroid#10]
使用yolov3－tiny.weights时app正常，但是换成yolov3.weights为什么会闪退呀？
还有程序里面是如何调用摄像头的啊

**Comment by nbdwddbf** [comment]
呃呃呃

**Comment by chentyjpm** [comment]
你考虑下你手机的内存够不够跑这个模型呢？

**Comment by nbdwddbf** [comment]
你好，谢谢回复！我是在小米平板上做的测试，刚刚看了一下，平板的运行内存有4个G呢 bfding 邮箱：bfding@cloume.com 签名由 网易邮箱大师 定制 在2018年10月26日 09:32，Christopher 写道： 你考虑下你手机的内存够不够跑这个模型呢？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by chentyjpm** [comment]
那你可以查看日志到底是啥原因

**Comment by shenyingying** [comment]
用自己训练的权重 代替你的 yolo-tiny.weight 出现闪退情况？请问博主知道这是什么情况吗？

**Comment by chentyjpm** [comment]
你需要具体问题具体分析 看报了什么错误
