### ISSUE TITLE
最新版本的android studio编译的时候报错

### ISSUE THREAD

**Issue by chenbocome** [chentyjpm/DarknetDemoInAndroid#11]
请问你用的NDK是哪个版本，我看网上的描述都是说这个是说我这边安装的NDK版本与这个工程不匹配的原因导致的。
**Describe the bug**
Build command failed.

Error while executing process F:\Software\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HG:\code\DarknetDemoInAndroid-master\app -BG:\code\DarknetDemoInAndroid-master\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-24 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=G:\code\DarknetDemoInAndroid-master\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=F:\Software\AppData\Local\Android\sdk\ndk-bundle -DCMAKE_C_FLAGS=-std=c99 -fopenmp  -DOMP_NUM_THREADS=8 -DCMAKE_CXX_FLAGS=-std=c++11 -frtti -fexceptions -fopenmp -DCMAKE_TOOLCHAIN_FILE=F:\Software\AppData\Local\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\Software\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=gcc}

 (include)   CMakeLists.txt 
Open File

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

-- Configuring incomplete, errors occurred!

Build command failed.

Error while executing process F:\Software\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HG:\code\DarknetDemoInAndroid-master\app -BG:\code\DarknetDemoInAndroid-master\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-24 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=G:\code\DarknetDemoInAndroid-master\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=F:\Software\AppData\Local\Android\sdk\ndk-bundle -DCMAKE_C_FLAGS=-std=c99 -fopenmp  -DOMP_NUM_THREADS=8 -DCMAKE_CXX_FLAGS=-std=c++11 -frtti -fexceptions -fopenmp -DCMAKE_TOOLCHAIN_FILE=F:\Software\AppData\Local\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\Software\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=gcc}

 (include)   CMakeLists.txt 
Open File

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

-- Configuring incomplete, errors occurred!

**Comment by chentyjpm** [comment]
应该就是最新版
