### ISSUE TITLE
内存泄漏有遇到吗？

### ISSUE THREAD

**Issue by jdTolerate** [chentyjpm/DarknetDemoInAndroid#21]
void forward_network(network *netp)
{
#ifdef GPU
    if(netp->gpu_index >= 0){
        LOGD("forward_network_gpu");
        forward_network_gpu(netp);
        return;
    }
#endif
    network net = *netp;
    int i;
    for(i = 0; i < net.n; ++i){
        net.index = i;
        layer l = net.layers[i];
        if(l.delta){
            LOGD("fill_cpu");
            fill_cpu(l.outputs * l.batch, 0, l.delta, 1);
        }
        l.forward(l, net);//这里有内存泄漏，注释此行内存泄漏消失
        net.input = l.output;
        if(l.truth) {
            net.truth = l.output;
        }
    }
    calc_network_cost(netp);
}

**Comment by jdTolerate** [comment]
https://github.com/pjreddie/darknet/pull/1056/commits/f89b2670a643b7a56bf7a622435b28996e173f3e

此方案可修复上述错误的内存泄漏。 
但还有一处内存泄漏
image **alphabet = load_alphabet();
此处载入lables文件，但 alphabet 并没有释放掉，会引起内存泄漏。
解决方案：
在test_detector函数return之前加释放内存：
if (alphabet){
        int x,y;
        for(y = 0; y < 8; ++y){
            for(x = 32; x < 127; ++x){
                free_image(alphabet[y][x]);
            }
        }
    }
即可。

**Comment by chentyjpm** [comment]
感谢 不过这个挺久了 都没更新了
