### ISSUE TITLE
工程跑起来，居然运行要96s 楼主指的是什么原因吗？

### ISSUE THREAD

**Issue by hecheng64** [chentyjpm/DarknetDemoInAndroid#5]
工程跑起来，居然运行要96s 楼主指的是什么原因吗？

**Comment by hecheng64** [comment]
05-22 17:18:06.279 20104-20465/com.example.chenty.demoyolo I/darknetlib: layer     filters    size              input                output
05-22 17:18:06.279 20104-20465/com.example.chenty.demoyolo I/darknetlib:     0 
05-22 17:18:06.280 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16
05-22 17:18:06.280 20104-20465/com.example.chenty.demoyolo I/darknetlib:     1 
05-22 17:18:06.280 20104-20465/com.example.chenty.demoyolo I/darknetlib: max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
05-22 17:18:06.280 20104-20465/com.example.chenty.demoyolo I/darknetlib:     2 
05-22 17:18:06.281 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32
05-22 17:18:06.281 20104-20465/com.example.chenty.demoyolo I/darknetlib:     3 
05-22 17:18:06.281 20104-20465/com.example.chenty.demoyolo I/darknetlib: max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
05-22 17:18:06.281 20104-20465/com.example.chenty.demoyolo I/darknetlib:     4 
05-22 17:18:06.284 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64
05-22 17:18:06.284 20104-20465/com.example.chenty.demoyolo I/darknetlib:     5 
05-22 17:18:06.284 20104-20465/com.example.chenty.demoyolo I/darknetlib: max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
05-22 17:18:06.284 20104-20465/com.example.chenty.demoyolo I/darknetlib:     6 
05-22 17:18:06.296 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128
05-22 17:18:06.296 20104-20465/com.example.chenty.demoyolo I/darknetlib:     7 
05-22 17:18:06.296 20104-20465/com.example.chenty.demoyolo I/darknetlib: max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
05-22 17:18:06.296 20104-20465/com.example.chenty.demoyolo I/darknetlib:     8 
05-22 17:18:06.344 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256
05-22 17:18:06.344 20104-20465/com.example.chenty.demoyolo I/darknetlib:     9 
05-22 17:18:06.344 20104-20465/com.example.chenty.demoyolo I/darknetlib: max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
05-22 17:18:06.344 20104-20465/com.example.chenty.demoyolo I/darknetlib:    10 
05-22 17:18:06.534 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512
05-22 17:18:06.534 20104-20465/com.example.chenty.demoyolo I/darknetlib:    11 
05-22 17:18:06.534 20104-20465/com.example.chenty.demoyolo I/darknetlib: max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
05-22 17:18:06.534 20104-20465/com.example.chenty.demoyolo I/darknetlib:    12 
05-22 17:18:07.298 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
05-22 17:18:07.298 20104-20465/com.example.chenty.demoyolo I/darknetlib:    13 
05-22 17:18:08.811 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
05-22 17:18:08.811 20104-20465/com.example.chenty.demoyolo I/darknetlib:    14 
05-22 17:18:08.831 20104-20465/com.example.chenty.demoyolo I/darknetlib: conv    125  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 125
05-22 17:18:08.831 20104-20465/com.example.chenty.demoyolo I/darknetlib:    15 
05-22 17:18:08.832 20104-20465/com.example.chenty.demoyolo I/darknetlib: detection
05-22 17:18:08.832 20104-20465/com.example.chenty.demoyolo I/darknetlib: mask_scale: Using default '1.000000'
05-22 17:18:08.832 20104-20465/com.example.chenty.demoyolo I/darknetlib: Loading weights from /sdcard/yolo/weights/tiny-yolo-voc.weights...
05-22 17:18:08.976 20104-20465/com.example.chenty.demoyolo I/darknetlib: Done!
05-22 17:19:46.214 20104-20465/com.example.chenty.demoyolo D/darknetlib: /sdcard/yolo/data/dog.jpg: Predicted in 96.987553 seconds.
05-22 17:19:46.219 20104-20465/com.example.chenty.demoyolo I/darknetlib: chair: 22%
05-22 17:19:46.220 20104-20465/com.example.chenty.demoyolo I/darknetlib: chair: 23%
05-22 17:19:46.221 20104-20465/com.example.chenty.demoyolo I/darknetlib: chair: 21%
05-22 17:19:46.222 20104-20465/com.example.chenty.demoyolo I/darknetlib: chair: 22%
05-22 17:19:46.223 20104-20465/com.example.chenty.demoyolo I/darknetlib: diningtable: 21%
05-22 17:19:46.226 20104-20465/com.example.chenty.demoyolo I/darknetlib: diningtable: 23%
05-22 17:19:47.254 20104-20465/com.example.chenty.demoyolo I/Yolo: yolo run time 96.98755264282227

**Comment by chentyjpm** [comment]
这种native程序最好不要使用DEBUG编译 release放手机里面跑试试看

**Comment by hecheng64** [comment]
谢谢 release 可以达到1.4s
